name: Continuous Delivery
on:
  push:
    branches:
      - main
jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
<<<<<<< Updated upstream
<<<<<<< Updated upstream

=======
        
>>>>>>> Stashed changes
=======
        
>>>>>>> Stashed changes
      - name: Simulando Continuous Delivery
        uses: actions/upload-artifact@v4
        with:
          name: projetozipado.zip
          path: |
            main.ipynb
<<<<<<< Updated upstream
<<<<<<< Updated upstream
            README.md  
=======
            README.md
>>>>>>> Stashed changes
=======
            README.md
>>>>>>> Stashed changes
